#application-credentials.yml

#S3_BUCKET_NAME:
#AWS_ACCESS_KEY:
#AWS_SECRET_KEY:

GPT_KEY: thisIsKey

JWT_KEY: "ThisIsASecretKeyAndShouldBeAtLeast32Charsckdkdkkskskkskskskkskskkskskaqqqqqq"

#Db_URL:
Db_URL: 127.0.0.1
Db_PORT: 3306
Db_User_Name: root
Db_User_PassWord: Kris2486!
Db_Name: localdb

#DDL_AUTO_MODE : none
#DDL_AUTO_MODE: create
DDL_AUTO_MODE: update

#SQL_INIT_MODE : always
SQL_INIT_MODE: never
